// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ora_cpp
Rcpp::DataFrame ora_cpp(const Rcpp::CharacterVector& gene, const Rcpp::CharacterVector& universe, const Rcpp::List& gene_sets, const Rcpp::CharacterVector& gene_set_names);
RcppExport SEXP _enrichit_ora_cpp(SEXP geneSEXP, SEXP universeSEXP, SEXP gene_setsSEXP, SEXP gene_set_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type gene(geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type universe(universeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type gene_set_names(gene_set_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ora_cpp(gene, universe, gene_sets, gene_set_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_enrichit_ora_cpp", (DL_FUNC) &_enrichit_ora_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_enrichit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
