// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ora_cpp
Rcpp::DataFrame ora_cpp(const Rcpp::CharacterVector& gene, const Rcpp::CharacterVector& universe, const Rcpp::List& gene_sets, const Rcpp::CharacterVector& gene_set_names);
RcppExport SEXP _enrichit_ora_cpp(SEXP geneSEXP, SEXP universeSEXP, SEXP gene_setsSEXP, SEXP gene_set_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type gene(geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type universe(universeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type gene_set_names(gene_set_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ora_cpp(gene, universe, gene_sets, gene_set_names));
    return rcpp_result_gen;
END_RCPP
}
// gsea_cpp
Rcpp::DataFrame gsea_cpp(const Rcpp::NumericVector& stats, const Rcpp::List& gene_sets, const Rcpp::CharacterVector& gene_set_names, int nPerm, double exponent, std::string method);
RcppExport SEXP _enrichit_gsea_cpp(SEXP statsSEXP, SEXP gene_setsSEXP, SEXP gene_set_namesSEXP, SEXP nPermSEXP, SEXP exponentSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type gene_set_names(gene_set_namesSEXP);
    Rcpp::traits::input_parameter< int >::type nPerm(nPermSEXP);
    Rcpp::traits::input_parameter< double >::type exponent(exponentSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(gsea_cpp(stats, gene_sets, gene_set_names, nPerm, exponent, method));
    return rcpp_result_gen;
END_RCPP
}
// gsea_adaptive_cpp
Rcpp::DataFrame gsea_adaptive_cpp(const Rcpp::NumericVector& stats, const Rcpp::List& gene_sets, const Rcpp::CharacterVector& gene_set_names, int minPerm, int maxPerm, double pvalThreshold, double exponent, std::string method);
RcppExport SEXP _enrichit_gsea_adaptive_cpp(SEXP statsSEXP, SEXP gene_setsSEXP, SEXP gene_set_namesSEXP, SEXP minPermSEXP, SEXP maxPermSEXP, SEXP pvalThresholdSEXP, SEXP exponentSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type gene_set_names(gene_set_namesSEXP);
    Rcpp::traits::input_parameter< int >::type minPerm(minPermSEXP);
    Rcpp::traits::input_parameter< int >::type maxPerm(maxPermSEXP);
    Rcpp::traits::input_parameter< double >::type pvalThreshold(pvalThresholdSEXP);
    Rcpp::traits::input_parameter< double >::type exponent(exponentSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(gsea_adaptive_cpp(stats, gene_sets, gene_set_names, minPerm, maxPerm, pvalThreshold, exponent, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_enrichit_ora_cpp", (DL_FUNC) &_enrichit_ora_cpp, 4},
    {"_enrichit_gsea_cpp", (DL_FUNC) &_enrichit_gsea_cpp, 6},
    {"_enrichit_gsea_adaptive_cpp", (DL_FUNC) &_enrichit_gsea_adaptive_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_enrichit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
