# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ora_cpp <- function(gene, universe, gene_sets, gene_set_names) {
    .Call(`_enrichit_ora_cpp`, gene, universe, gene_sets, gene_set_names)
}

gsea_cpp <- function(stats, gene_sets, gene_set_names, nPerm = 1000L, exponent = 1.0, method = "sample", seed = 12345L) {
    .Call(`_enrichit_gsea_cpp`, stats, gene_sets, gene_set_names, nPerm, exponent, method, seed)
}

gsea_adaptive_cpp <- function(stats, gene_sets, gene_set_names, minPerm = 1000L, maxPerm = 100000L, pvalThreshold = 0.1, exponent = 1.0, method = "sample", seed = 12345L) {
    .Call(`_enrichit_gsea_adaptive_cpp`, stats, gene_sets, gene_set_names, minPerm, maxPerm, pvalThreshold, exponent, method, seed)
}

gsea_multilevel_cpp <- function(geneList, gene_sets, gene_set_names, minPerm, maxPerm, pvalThreshold, exponent, method, eps, sampleSize, seed, nPermSimple = 1000L, scoreType = "std") {
    .Call(`_enrichit_gsea_multilevel_cpp`, geneList, gene_sets, gene_set_names, minPerm, maxPerm, pvalThreshold, exponent, method, eps, sampleSize, seed, nPermSimple, scoreType)
}

gsea_scores_cpp <- function(stats, in_set, exponent) {
    .Call(`_enrichit_gsea_scores_cpp`, stats, in_set, exponent)
}

gsea_es_all_cpp <- function(stats, gene_sets, exponent, scoreType) {
    .Call(`_enrichit_gsea_es_all_cpp`, stats, gene_sets, exponent, scoreType)
}

#' Random Walk with Restart using Eigen Sparse Matrix
#'
#' @param A column-normalized sparse matrix
#' @param v initial restart vector
#' @param restart restart probability (e.g., 0.5)
#' @param threshold convergence threshold
#' @param max_iter maximal number of iterations
#' @return list containing stationary probabilities and iterations
#' @noRd
rwr_eigen_cpp <- function(A, v, restart, threshold, max_iter) {
    .Call(`_enrichit_rwr_eigen_cpp`, A, v, restart, threshold, max_iter)
}

#' Effects matrix from .lmEffects (contrast coordinate + residual coordinates)
#'
#' @keywords internal
st_effects_cpp <- function(E, weights, design, contrast_idx) {
    .Call(`_enrichit_st_effects_cpp`, E, weights, design, contrast_idx)
}

#' limma-style squeezeVar for scalar residual df (fitFDist prior)
#'
#' @keywords internal
st_squeeze_var_cpp <- function(var, df) {
    .Call(`_enrichit_st_squeeze_var_cpp`, var, df)
}

#' Native camera: inter-gene-correlation adjusted mean-rank set test
#'
#' Mirrors \code{limma::camera} for \code{use.ranks = FALSE}.
#'
#' @keywords internal
st_camera_cpp <- function(E, weights, design, contrast_idx, index, inter_gene_cor, allow_neg_cor) {
    .Call(`_enrichit_st_camera_cpp`, E, weights, design, contrast_idx, index, inter_gene_cor, allow_neg_cor)
}

#' Native roast: rotation gene set test on the effects matrix
#'
#' Mirrors \code{limma::mroast}/\code{.roastEffects} with scalar
#' var.prior/df.prior and \code{approx.zscore = TRUE}. Consumes R's
#' RNG in the same order as limma, so \code{set.seed()} reproduces
#' limma's rotation draws exactly.
#'
#' @keywords internal
st_roast_cpp <- function(E, weights, design, contrast_idx, index, set_statistic, gene_weights, nrot) {
    .Call(`_enrichit_st_roast_cpp`, E, weights, design, contrast_idx, index, set_statistic, gene_weights, nrot)
}

#' Native fry: fast rotation-free set test on the effects matrix
#'
#' Mirrors \code{limma::fry} (standardize = "posterior.sd" by default).
#'
#' @keywords internal
st_fry_cpp <- function(E, weights, design, contrast_idx, index, gene_weights, standardize) {
    .Call(`_enrichit_st_fry_cpp`, E, weights, design, contrast_idx, index, gene_weights, standardize)
}

