# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ora_cpp <- function(gene, universe, gene_sets, gene_set_names) {
    .Call(`_enrichit_ora_cpp`, gene, universe, gene_sets, gene_set_names)
}

